### ISSUE TITLE
Install ZoneMTA 

### ISSUE THREAD

**Issue by victorbrunetti** [zone-eu/zone-mta#147]
Hello.

Im trying to install Zone MTA but im getting some errors.

nodejs -v
v8.11.3

 mongod --version
db version v3.6.5

i got a vps ans just run

$ git clone git://github.com/zone-eu/zone-mta-template.git
$ cd zone-mta-template
$ npm install --production
$ npm start

and them

Can u help me to install and config ??? do you have skype?

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:88:17)
    at SMTPServer.updateSecureContext (/zone-mta-template/node_modules/smtp-serv                                                                                        er/lib/smtp-server.js:233:41)
    at new SMTPServer (/zone-mta-template/node_modules/smtp-server/lib/smtp-serv                                                                                        er.js:27:14)
    at getKeyfiles (/zone-mta-template/node_modules/zone-mta/lib/smtp-interface.                                                                                        js:287:31)
    at ReadFileContext.getFile [as callback] (/zone-mta-template/node_modules/zo                                                                                        ne-mta/lib/smtp-interface.js:92:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
ERR! SMTP/feeder/43567 Reciver process 544f1c598f5c19695f0b for feeder exited wi                                                                                        th 1
info Sender/default/43572 [a4e9b3a17d905309b047] Starting sending for default
the options [useNewUrlParser] is not supported
info Child/bounces/43589 [52454d92072b46437f78] Spawning sender process for boun                                                                                        ces
info Sender/bounces/43589 [52454d92072b46437f78] Starting sending for bounces
the options [useNewUrlParser] is not supported
the options [useNewUrlParser] is not supported
info SMTP/feeder/43600 3 plugins loaded
_tls_common.js:88
      c.context.setCert(options.cert);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:88:17)
    at SMTPServer.updateSecureContext (/zone-mta-template/node_modules/smtp-serv                                                                                        er/lib/smtp-server.js:233:41)
    at new SMTPServer (/zone-mta-template/node_modules/smtp-server/lib/smtp-serv                                                                                        er.js:27:14)
    at getKeyfiles (/zone-mta-template/node_modules/zone-mta/lib/smtp-interface.                                                                                        js:287:31)
    at ReadFileContext.getFile [as callback] (/zone-mta-template/node_modules/zo                                                                                        ne-mta/lib/smtp-interface.js:92:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
ERR! SMTP/feeder/43600 Reciver process c542677ba7ceff661c58 for feeder exited wi                                                                                        th 1

**Comment by andris9** [comment]
Should work now, try again with latest commit
