### ISSUE TITLE
1.10.1 breaks prometheus

### ISSUE THREAD

**Issue by dazoot** [zone-eu/zone-mta#151]
Seems there is an error when upgrading to 1.10.1:

```Error: Added label "status" is not included in initial labelset: [ 'result' ]```

**Comment by andris9** [comment]
Check that you are actually using v1.10.1. The bug landed in 1.10.0 and was fixed by 1.10.1. If you are using v1.10.1 and still have it, then could you provide the full stack trace of the error?

**Comment by dazoot** [comment]
I am using the latest version:

```
Jul 31 11:37:16 mhost1 zone-mta: info App  ----------------------- zone-mta@1.10.1 -----------------------
```

```
Jul 31 11:37:20 mhost1 zone-mta: info Sender/default/17238[2] 164efb12fb8000d448.001 SMTPCLOSE [QWzss9R8SKA] Connection closed response="250 2.0.0 Ok: queued as 85BAD123B4F"
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process Uncaught exception
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process Error: Added label "status" is not included in initial labelset: [ 'result' ]
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at Object.keys.forEach.label (/usr/local/zonemta/node_modules/prom-client/lib/validation.js:26:10)
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at Array.forEach (native)
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at validateLabel (/usr/local/zonemta/node_modules/prom-client/lib/validation.js:24:22)
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at /usr/local/zonemta/node_modules/prom-client/lib/counter.js:147:3
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at Counter.inc (/usr/local/zonemta/node_modules/prom-client/lib/counter.js:93:38)
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at Connection.client.onData (/usr/local/zonemta/node_modules/zone-mta/lib/queue-server.js:146:47)
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at FrameParser.Connection.parser.E [as handler] (/usr/local/zonemta/node_modules/zone-mta/lib/transport/connection.js:23:18)
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at FrameParser.processFrame (/usr/local/zonemta/node_modules/zone-mta/lib/transport/frame-parser.js:112:14)
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at Immediate.setImmediate (/usr/local/zonemta/node_modules/zone-mta/lib/transport/frame-parser.js:106:40)
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at runCallback (timers.js:672:20)
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at tryOnImmediate (timers.js:645:5)
Jul 31 11:37:20 mhost1 zone-mta: ERR! Process     at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by andris9** [comment]
Could you check line nr 16 of this file: /usr/local/zonemta/node_modules/zone-mta/lib/queue-server.js

The line should look like this: `labelNames: ['status']`

If the line is different (there is 'result' instead of status), then its the older buggy version.

**Comment by dazoot** [comment]
It's with result:
```
    labelNames: ['result']
```

Could be that you didnot commit the change ?

**Comment by andris9** [comment]
It is changed in [git](https://github.com/zone-eu/zone-mta/blob/f2e1d976d74f87dac2843526ff313d4d37b0901e/lib/queue-server.js#L16) and I also get correct code when running "npm install zone-mta"

```
$ npm install zone-mta
$sed '16!d'  node_modules/zone-mta/lib/queue-server.js
    labelNames: ['status']
```

**Comment by dazoot** [comment]
Hmm. Could it be npm issue ?

**Comment by andris9** [comment]
Maybe some caching issue or something, I pushed out v1.10.1 only a few minutes after v1.10.0 when I discovered the bug.

**Comment by dazoot** [comment]
I will close this since it seems it's internal deb build issue rather than zonemta one.
