### ISSUE TITLE
hangs when starting up, and does not continue

### ISSUE THREAD

**Issue by visomymail** [zone-eu/zone-mta#153]
o App  ----------------------- zone-mta@1.10.4 -----------------------
info App
info SMTP/feeder SMTP feeder MTA server started listening on port 2525
info QS Queue server started
info API API server started
info mongo Setup 10 indexes
info Queue Sending queue initialized
info Child/default/2476 [857c1a7787b4c9a65364] Spawning sender process for defau                                            lt
info SMTP/feeder/2475 3 plugins loaded
info SMTP/feeder/2475 SMTP feeder MTA server started
info Sender/default/2476 [857c1a7787b4c9a65364] Starting sending for default
info Child/bounces/2499 [90bbc9daab38777d86f8] Spawning sender process for bounc                                            es
info Sender/bounces/2499 [90bbc9daab38777d86f8] Starting sending for bounces
----------------------------
does not continue

**Comment by visomymail** [comment]
apparently this is for the Internet, I tried on another computer gives a lot of errors, tell me what is wrong?
------------------------------------------------------------------
info App ---------------------------------------------------------------
info App
info App ███████╗ ██████╗ ███╗ ██╗███████╗███╗ ███╗████████╗ █████╗
info App ╚══███╔╝██╔═══██╗████╗ ██║██╔════╝████╗ ████║╚══██╔══╝██╔══██╗
info App ███╔╝ ██║ ██║██╔██╗ ██║█████╗ ██╔████╔██║ ██║ ███████║
info App ███╔╝ ██║ ██║██║╚██╗██║██╔══╝ ██║╚██╔╝██║ ██║ ██╔══██║
info App ███████╗╚██████╔╝██║ ╚████║███████╗██║ ╚═╝ ██║ ██║ ██║ ██║
info App ╚══════╝ ╚═════╝ ╚═╝ ╚═══╝╚══════╝╚═╝ ╚═╝ ╚═╝ ╚═╝ ╚═╝
info App
info App ----------------------- zone-mta@1.10.4 -----------------------
info App
ERR! SMTP/feeder Could not start feeder MTA server
ERR! SMTP/feeder Error: listen EADDRINUSE 127.0.0.1:2525
ERR! SMTP/feeder at Object._errnoException (util.js:992:11)
ERR! SMTP/feeder at _exceptionWithHostPort (util.js:1014:20)
ERR! SMTP/feeder at Server.setupListenHandle [as _listen2] (net.js:1355:14)
ERR! SMTP/feeder at listenInCluster (net.js:1396:12)
ERR! SMTP/feeder at doListen (net.js:1505:7)
ERR! SMTP/feeder at _combinedTickCallback (internal/process/next_tick.js:141 :11)
ERR! SMTP/feeder at process._tickDomainCallback (internal/process/next_tick. js:218:9)
ERR! SMTP/feeder { Error: listen EADDRINUSE 127.0.0.1:2525
ERR! SMTP/feeder at Object._errnoException (util.js:992:11)
ERR! SMTP/feeder at _exceptionWithHostPort (util.js:1014:20)
ERR! SMTP/feeder at Server.setupListenHandle [as _listen2] (net.js:1355:14)
ERR! SMTP/feeder at listenInCluster (net.js:1396:12)
ERR! SMTP/feeder at doListen (net.js:1505:7)
ERR! SMTP/feeder at _combinedTickCallback (internal/process/next_tick.js:141 :11)
ERR! SMTP/feeder at process._tickDomainCallback (internal/process/next_tick. js:218:9)
ERR! SMTP/feeder stack: 'Error: listen EADDRINUSE 127.0.0.1:2525\n at Objec t._errnoException (util.js:992:11)\n at _exceptionWithHostPort (util.js:1014: 20)\n at Server.setupListenHandle [as _listen2] (net.js:1355:14)\n at list enInCluster (net.js:1396:12)\n at doListen (net.js:1505:7)\n at _combinedT ickCallback (internal/process/next_tick.js:141:11)\n at process._tickDomainCa llback (internal/process/next_tick.js:218:9)',
ERR! SMTP/feeder code: 'EADDRINUSE',
ERR! SMTP/feeder errno: 'EADDRINUSE',
ERR! SMTP/feeder syscall: 'listen',
ERR! SMTP/feeder address: '127.0.0.1',
ERR! SMTP/feeder port: 2525 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zone-mta-template@1.4.1 start: `node index.js --config=config/zonemta.t oml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zone-mta-template@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-08-23T14_41_28_906Z-debug.log
