### ISSUE TITLE
ipv6 undefined error

### ISSUE THREAD

**Issue by JQuags** [zone-eu/zone-mta#246]
I have zmta working fine with ipv4. When enabling ipv6 and setting

preferIPv6=true
ignoreIPv6=false

in the default zone I get an undefined error:

@400000005f214943089e4a8c /usr/home/zone/zone-mta-template/node_modules/zone-mta/lib/sender.js:829
@400000005f214943089e4e74             delivery.connectionKey = delivery.connectionKey || [delivery.zoneAddress.address, this.zone.host || delivery.domain, delivery.mxPort].join(':');
@400000005f214943089e525c                                                                                      ^
@400000005f214943089e5644
@400000005f214943089e5a2c TypeError: Cannot read property 'address' of undefined
@400000005f214943089e5a2c     at tryConnect (/usr/home/zone/zone-mta-template/node_modules/zone-mta/lib/sender.js:829:86)
@400000005f214943089f34ec     at Sender.getConnection (/usr/home/zone/zone-mta-template/node_modules/zone-mta/lib/sender.js:1098:9)
@400000005f214943089f38d4     at /usr/home/zone/zone-mta-template/node_modules/zone-mta/lib/sender.js:737:22
@400000005f214943089f38d4     at /usr/home/zone/zone-mta-template/node_modules/zone-mta/lib/sender.js:69:45
@400000005f214943089f3cbc     at Immediate.<anonymous> (/usr/home/zone/zone-mta-template/node_modules/zone-mta/services/sender.js:101:32)
@400000005f214943089fd8fc     at processImmediate (internal/timers.js:456:21)
@400000005f2149430921fd64 ERR! Child/default/66264 [4923afd3e2e5a0c4f3b8] Sender process for default exited with 1

I see delivery.zoneAddressIPv6.address is defined with the correct address but delivery.zoneAddress.address is being called in sender.js.

**Comment by jpbede** [comment]
This is a bug within the connection pooling. The PR https://github.com/zone-eu/zone-mta/pull/277 should fix this.
