### ISSUE TITLE
Uncaught exception when deleting from queue

### ISSUE THREAD

**Issue by behemoth88** [zone-eu/zone-mta#279]
Hello.
When a message from queue gets deleted, an error is thrown:
```
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process Uncaught exception
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process MongoInvalidArgumentError: Method "collection.find()" accepts at most two arguments
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process     at Collection.find (/opt/zone-mta-template/node_modules/mongodb/lib/collection.js:238:19)
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process     at MailQueue.remove (/opt/zone-mta-template/node_modules/zone-mta/lib/mail-queue.js:576:20)
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process     at /opt/zone-mta-template/node_modules/zone-mta/lib/api-server.js:455:24
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process     at nextTick (/opt/zone-mta-template/node_modules/restify/lib/chain.js:167:13)
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process     at processTicksAndRejections (internal/process/task_queues.js:77:11)
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process  MongoInvalidArgumentError: Method "collection.find()" accepts at most two arguments
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process     at Collection.find (/opt/zone-mta-template/node_modules/mongodb/lib/collection.js:238:19)
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process     at MailQueue.remove (/opt/zone-mta-template/node_modules/zone-mta/lib/mail-queue.js:576:20)
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process     at /opt/zone-mta-template/node_modules/zone-mta/lib/api-server.js:455:24
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process     at nextTick (/opt/zone-mta-template/node_modules/restify/lib/chain.js:167:13)
Sep 20 13:00:58 server.hostname.net node[5706]: ERR! Process     at processTicksAndRejections (internal/process/task_queues.js:77:11)
Sep 20 13:00:58 server.hostname.net node[5706]: info Process Server closing down...
```
Node version: v16.9.1
Same issue on version v14.

**Comment by andris9** [comment]
fixed by f6659b137352e47d9a228ea5fc15176ed79c2dc5
