### ISSUE TITLE
Send from trusted ips withtout authentication and with authentication from all other ips

### ISSUE THREAD

**Issue by matteomattei** [zone-eu/zone-mta#285]
Hello,
I need to send messges directly without authentication from some IP and with authentication from all other IP.
I enabled authentication and created a plugin:

```
"use strict";
const mysql = require("mysql");

module.exports.title = "MySQL Authentication";
module.exports.init = (app, done) => {
  const pool = mysql.createPool({
    connectionLimit: 10,
    host: "127.0.0.1",
    user: "root",
    password: "aeChaengee5Ohz6r",
    database: "users",
  });

  app.addHook("smtp:connect", (session, next) => {
    if (!app.config.interfaces.includes(session.interface)) {
      // not an interface we care about
      next();
    }
    console.log("SMTP_CONNECT", session);
    let sql = `select count(0) as found from relay_by_ip where ip = ${pool.escape(
      session.remoteAddress
    )}`;
    pool.query(sql, (err, res) => {
      if (err || !res || res.length === 0) {
        let error = new Error("Wrong configuration");
        error.responseCode = 535;
        return next(error);
      }
      if (res[0].found === 1) {
        session.ip_relay_allowed = true;
      } else {
        session.ip_relay_allowed = false;
      }
      return next();
    });
  });

  // Listen for AUTH command
  app.addHook("smtp:auth", (auth, session, next) => {
    if (!app.config.interfaces.includes(session.interface)) {
      // not an interface we care about
      next();
    }
    console.log("SMTP_AUTH", session);
    if (session.ip_relay_allowed) {
      return next();
    }
    let sql = `select password, status from auths where username=${pool.escape(
      auth.username
    )}`;
    pool.query(sql, (err, res) => {
      if (err) {
        let error = new Error("Wrong configuration");
        error.responseCode = 535;
        return next(error);
      }
      if (!res || res.length === 0) {
        let error = new Error("Authentication failed - user not found");
        error.responseCode = 535;
        return next(error);
      }
      if (auth.password !== res[0].password) {
        let error = new Error("Authentication failed - wrong credentials");
        error.responseCode = 535;
        return next(error);
      }
      if (res[0].status === 0) {
        let error = new Error("Authentication failed - user disabled");
        error.responseCode = 535;
        return next(error);
      }
      return next();
    });
  });

  done();
};
```

However, even if I use an allowed IP address (having the session.ip_relay_allowed = true) and try to send without authentication:

```
"use strict";
const nodemailer = require("nodemailer");

async function main() {
  let transporter = nodemailer.createTransport({
    host: "xxx.xxx.xxx.xxx",
    port: 2525,
    secure: false
//    auth: {
//      user: 'xxxxxx',
//      pass: 'xxxxxx'
//    },
  });

  let info = await transporter.sendMail({
    from: 'foo@example.com',
    to: 'hello@domain.com',
    subject: "Hello",
    text: "Hello world",
    html: "<b>Hello world</b>"
  });

  console.log("Message sent: %s", info.messageId);
}

main().catch(console.error);
```

I always get:

```
code: 'EENVELOPE',
response: '530 Error: authentication Required',
responseCode: 530,
command: 'MAIL FROM'
```

and the "smtp:auth" hook is never called.
Looking at `smtp-server/lib/smtp-connection.js` I see the error is generated by this:

```
// Check if authentication is required
        if (!this.session.user && this._isSupported('AUTH') && ['MAIL', 'RCPT', 'DATA'].includes(commandName) && !this._server.options.authOptional) {
            this.send(530, 'Error: authentication Required');
            return setImmediate(callback);
        }
```

this is because "user" is not provided... is there a way to do it?
Thanks

**Comment by andris9** [comment]
By default authentication if enabled is mandatory. You can disable it by providing an additional configuration argument for the SMTP interface: `authOptional: true`

```toml
[feeder]
enabled=true
host="0.0.0.0"
port=2525
authentication=true
authOptional=true
#...
```

It would probably be easier for you to set up 2 SMTP interfaces, one with authentication and the other without authentication but firewalled to only allow connections from some specific IP address.

```toml
# authenticated interface
[feeder]
enabled=true
host="0.0.0.0"
port=2525
authentication=true
#...

# unauthenticated interface
[whitelisted]
enabled=true
host="0.0.0.0"
port=2526 # must either use another port or IP than the default
authentication=false
#...
```

**Comment by matteomattei** [comment]
Thanks @andris9 but blocking some ip from the firewall is not a doable path for us.
So I tried the authOptional=true and it works... but now I have another issue.
I want to intercept in someway if a connection happens with authentication or not:

- if the connection happens without authentication, I would check in database to see if the IP is allowed, otherwise I block it.
- if the connection happens with authentication, I would check in the database for user credentials and block if they are not right.

I see the hooks are called in this order:

smtp:connection
smtp:auth <-- never called if no authentication data are passed
smtp:data

I added some debug lines (console.log) to the three hooks above and noticed that smtp:data reported also a field called "user" in the envelop object. So I thought that I might check that field in the smtp:data hook because if no authentication is passed, that field is always "undefined" while is defined with the actual username if the authentication is provided.

However, the problem now is that if I trigger an error inside the smtp:data hook, it is not propagated to the client but the client waits something forever until a timeout is triggered:

```
  app.addHook("smtp:data", (envelope, session, next) => {
    if (!app.config.interfaces.includes(session.interface)) {
      return next();
    }
    console.log("SMTP_DATA", envelope, session);
    let error = new Error("Always error");
    error.responseCode = 535;
    return next(error);
  });
```

```
matteo@barracuda ~/src/test/nodemailer $ node send.js 
Error: Timeout
    at SMTPConnection._onTimeout (/home/matteo/src/test/nodemailer/node_modules/nodemailer/lib/smtp-connection/index.js:847:30)
    at Socket.SMTPConnection._onSocketTimeout (/home/matteo/src/test/nodemailer/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)
    at Socket.emit (events.js:400:28)
    at Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
```
Do you have any idea?
