### ISSUE TITLE
Unable to scrape metrics

### ISSUE THREAD

**Issue by nahsi** [zone-eu/zone-mta#291]
When I try to access metrics endpoint I get this:
```shell
> curl -sS zone-mta.service.consul:26740/metrics | jq
```
```json
{
    "code": "InternalServer",
    "message": "reached the end of the handler chain without writing a response!"
}
```
I suspect there is some misconfiguration from my side. I haven't set it up fully yet - I always try to setup monitoring first because it helps debugging.

When I try to access from browser it crushes. Please help me good people

Full log:
```
info App  ---------------------------------------------------------------
info App 
info App  ███████╗ ██████╗ ███╗   ██╗███████╗███╗   ███╗████████╗ █████╗ 
info App  ╚══███╔╝██╔═══██╗████╗  ██║██╔════╝████╗ ████║╚══██╔══╝██╔══██╗
info App    ███╔╝ ██║   ██║██╔██╗ ██║█████╗  ██╔████╔██║   ██║   ███████║
info App   ███╔╝  ██║   ██║██║╚██╗██║██╔══╝  ██║╚██╔╝██║   ██║   ██╔══██║
info App  ███████╗╚██████╔╝██║ ╚████║███████╗██║ ╚═╝ ██║   ██║   ██║  ██║
info App  ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝     ╚═╝   ╚═╝   ╚═╝  ╚═╝
info App 
info App  ------------------------ zone-mta@3.2.4 -----------------------
info App 
(node:1) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
info SMTP/feeder SMTP feeder MTA server started listening on port 587
info QS Queue server started
info API API server started
info Service Changed group to "nobody" (65534)
info Service Changed user to "nobody" (65534)
info Redis/1 Redis ready to take connections
verb mongo Skipped index 1 "mail.files.mailupload": No index added
verb mongo Skipped index 2 "mail.files.mailfile": No index added
verb mongo Skipped index 3 "suppressionlist.suppressed_address": No index added
verb mongo Skipped index 4 "suppressionlist.suppressed_domain": No index added
verb mongo Skipped index 5 "suppressionlist.list_by_newer": No index added
verb mongo Skipped index 6 "zone-queue.findall": No index added
verb mongo Skipped index 7 "zone-queue.search_next": No index added
verb mongo Skipped index 8 "zone-queue.find_all_queued": No index added
verb mongo Skipped index 9 "zone-queue.delivery": No index added
verb mongo Skipped index 10 "zone-queue.message_locking": No index added
info mongo Setup 10 indexes
info Queue Sending queue initialized
info Child/default/19 [8bdefc2893ecda20683e] Spawning sender process for default
info Sender/default/19 [8bdefc2893ecda20683e] Starting sending for default
info ConnPool/19 Connection pool is ready to take connections
info Redis/13 Redis ready to take connections
info Redis/12 Redis ready to take connections
info Redis/19 Redis ready to take connections
info Plugins/receiver/13 Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 10ms]
info Plugins/receiver/12 Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 12ms]
info Plugins/sender/19 Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 5ms]
info Plugins/sender/19 Initialized WildDuck MSA from <node_modules/zonemta-wildduck> [load time 339ms]
verb Sender/default/19 2 plugins loaded
verb Child/default/19 [8bdefc2893ecda20683e] Sender process for default ready to take messages
info Child/bounces/45 [43a0d74126149036d611] Spawning sender process for bounces
info Plugins/receiver/12 Initialized WildDuck MSA from <node_modules/zonemta-wildduck> [load time 360ms]
info SMTP/feeder/12 2 plugins loaded
info Plugins/receiver/13 Initialized WildDuck MSA from <node_modules/zonemta-wildduck> [load time 365ms]
info SMTP/feeder/13 2 plugins loaded
info Redis/13 Redis ready to take connections
info Redis/12 Redis ready to take connections
verb Sender/default/19[1] Created sender instance for default
info SMTP/feeder/13 SMTP feeder MTA server started
info SMTP/feeder/12 SMTP feeder MTA server started
verb Sender/default/19[2] Created sender instance for default
info Sender/bounces/45 [43a0d74126149036d611] Starting sending for bounces
info ConnPool/45 Connection pool is ready to take connections
info Redis/45 Redis ready to take connections
verb Sender/default/19[3] Created sender instance for default
verb Sender/default/19[4] Created sender instance for default
verb Sender/default/19[5] Created sender instance for default
verb Sender/default/19[6] Created sender instance for default
info Plugins/sender/45 Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 4ms]
verb Sender/default/19[7] Created sender instance for default
verb Sender/default/19[8] Created sender instance for default
verb Sender/default/19[9] Created sender instance for default
verb Sender/default/19[10] Created sender instance for default
info Plugins/sender/45 Initialized WildDuck MSA from <node_modules/zonemta-wildduck> [load time 282ms]
verb Sender/bounces/45 2 plugins loaded
verb Child/bounces/45 [43a0d74126149036d611] Sender process for bounces ready to take messages
info Plugins/main/1 Initialized Default headers from <node_modules/zone-mta/plugins/core/default-headers> [load time 6ms]
info Plugins/main/1 Initialized Email Bounce Notification from <node_modules/zone-mta/plugins/core/email-bounce> [load time 0ms]
verb Plugins Plugins loaded
verb Sender/bounces/45[1] Created sender instance for bounces
verb HTTP /metrics
verb HTTP /metrics
verb HTTP /metrics
verb HTTP /metrics
verb HTTP /
verb HTTP /favicon.ico
verb HTTP /metrics
ERR! Process Uncaught exception
ERR! Process Error [ERR_STREAM_WRITE_AFTER_END]: write after end
ERR! Process     at new NodeError (node:internal/errors:371:5)
ERR! Process     at _write (node:internal/streams/writable:320:11)
ERR! Process     at Gzip.Writable.end (node:internal/streams/writable:610:17)
ERR! Process     at /usr/local/zone-mta/node_modules/zone-mta/lib/api-server.js:690:38
ERR! Process     at runMicrotasks (<anonymous>)
ERR! Process     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR! Process  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
ERR! Process     at new NodeError (node:internal/errors:371:5)
ERR! Process     at _write (node:internal/streams/writable:320:11)
ERR! Process     at Gzip.Writable.end (node:internal/streams/writable:610:17)
ERR! Process     at /usr/local/zone-mta/node_modules/zone-mta/lib/api-server.js:690:38
ERR! Process     at runMicrotasks (<anonymous>)
ERR! Process     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
ERR! Process   code: 'ERR_STREAM_WRITE_AFTER_END'
ERR! Process }
info Process Server closing down...
info Service closed
ERR! ERR!Sender/default/19 Connection to Queue server closed unexpectedly
 SMTP/feeder/13 Connection to Queue server closed unexpectedly
ERR! Sender/bounces/45 Connection to Queue server closed unexpectedly
ERR! SMTP/feeder/12 Connection to Queue server closed unexpectedly
info QS Service closed
ERR! Process Uncaught exception
ERR! Process MongoNotConnectedError: MongoClient must be connected to perform this operation
ERR! Process     at Object.getTopology (/usr/local/zone-mta/node_modules/mongodb/lib/utils.js:391:11)
ERR! Process     at Collection.find (/usr/local/zone-mta/node_modules/mongodb/lib/collection.js:243:53)
ERR! Process     at MailQueue.queuCounterUpdate (/usr/local/zone-mta/node_modules/zone-mta/lib/mail-queue.js:1026:14)
ERR! Process     at Timeout.<anonymous> (/usr/local/zone-mta/node_modules/zone-mta/lib/mail-queue.js:1010:59)
ERR! Process     at listOnTimeout (node:internal/timers:557:17)
ERR! Process     at processTimers (node:internal/timers:500:7)
ERR! Process  MongoNotConnectedError: MongoClient must be connected to perform this operation
ERR! Process     at Object.getTopology (/usr/local/zone-mta/node_modules/mongodb/lib/utils.js:391:11)
ERR! Process     at Collection.find (/usr/local/zone-mta/node_modules/mongodb/lib/collection.js:243:53)
ERR! Process     at MailQueue.queuCounterUpdate (/usr/local/zone-mta/node_modules/zone-mta/lib/mail-queue.js:1026:14)
ERR! Process     at Timeout.<anonymous> (/usr/local/zone-mta/node_modules/zone-mta/lib/mail-queue.js:1010:59)
ERR! Process     at listOnTimeout (node:internal/timers:557:17)
ERR! Process     at processTimers (node:internal/timers:500:7)
info Process Force closing...
```

Config:
```
# https://github.com/zone-eu/zone-mta/blob/master/config/default.js
name="ZoneMTA"
ident="zone-mta"

user="nobody"
group="nobody"

[log]
level="debug"

[dbs]
# @include "/secrets/config/dbs.toml"

[queue]
instanceId='mail.zone-mta[1]'

collection="zone-queue"
gfs="mail"

[dns]
caching=false
nameservers=["1.1.1.1", "8.8.8.8"]

[api]
host="0.0.0.0"
port=26740
hostname="zone-mta.service.consul"
maildrop=false

[plugins]
# @include "plugins/*.toml"

[smtpInterfaces]
# @include "interfaces/*.toml"
```

**Comment by Bianconiglio** [comment]
Hi,
i have the same problem, metrics dont work and error message like you, do y have find solution?

**Comment by nahsi** [comment]
@Bianconiglio unfortunately no, living without metrics now :(

**Comment by vhenon** [comment]
Hello, I found a workaround

On your repo deployment, you need to tweak the file `node_modules/zone-mta/lib/api-server.js` and add `async/await` keys to `/metrics` route

```shell
this.server.get('/metrics', async (req, res, next) => {
    await promClient.register
```

However, to work properly, you need to comment restify gzip pluging

```shell
//this.server.use(restify.plugins.gzipResponse());
```

It's not perfect, but you will be able to scrape metrics

**Comment by Bianconiglio** [comment]
Hi,
in my case not working after restart there is this problem:

/opt/zone-mta/node_modules/zone-mta/lib/api-server.js:688
            await promClient.register
             ^^^^^
            SyntaxError: await is only valid in async functions and the top level bodies of modules at Object.compileFunction (node:vm:352:18)

on :

this.server.get('/metrics', async (req, res, next) => {
    await promClient.register

**Comment by Bianconiglio** [comment]
Works !! thank you very much for helping

**Comment by randrusiak** [comment]
Thanks! It works, but maybe it will be a good idea to fix it directly in the project source code? :)
