### ISSUE TITLE
DKIM error:1E08010C:DECODER routines::unsupported

### ISSUE THREAD

**Issue by akhil** [zone-eu/zone-mta#375]
After setting up the DKIM keys I am getting the following error. I am getting the error with both 1024 and 2048 keys.

```
Error: error:1E08010C:DECODER routines::unsupported
    at Sign.sign (node:internal/crypto/sig:128:29)
    at module.exports.sign (/root/zone-mta-template/node_modules/zone-mta/lib/dkim-sign.js:55:28)
    at /root/zone-mta-template/node_modules/zone-mta/lib/sender.js:1436:39
    at Array.forEach (<anonymous>)
    at Sender.signMessage (/root/zone-mta-template/node_modules/zone-mta/lib/sender.js:1434:14)
    at /root/zone-mta-template/node_modules/zone-mta/lib/sender.js:351:38
    at /root/zone-mta-template/node_modules/zone-mta/lib/plugin-handler.js:499:25 {
  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'
}
```

**Comment by andris9** [comment]
The key is probably in a wrong format. For example you did not provide the actual key but the path to the file or smth like that.
