### ISSUE TITLE
Mail stucked on status queued, won't be delivered

### ISSUE THREAD

**Issue by avensonk** [zone-eu/zone-mta#383]
I'm new to email service provider, based on the demand of company I has been assigned to doing MTA. I done the installation and configuration. When I tried to send the email by using ZoneMTA but the email has stucked in queue never be sending, I am exploring the solution but not get an answer. Does anyone can guide me with this issue?

info Queue/22996 id=undefined 18e9d13c9950003872 QUEUED (message-id=<a347e4e7-7340-ccf7-f4c4-537fd099f47c@go2buy.my> from=noreply@go2buy.my to=steven.kee@kumoten.com src=127.0.0.1 subject="TEST zoneMTA Email" body=14 md5=ae08177a267c)
info Sender/default/18240[2] id=auephj3hlr7wsux3 18e9d13c9950003872.001 CONNECTING domain=kumoten.com port=2525
C:\Users\Administrator\Desktop\zone-mta\lib\sender.js:1029
            delivery.connectionKey = delivery.connectionKey || [zoneAddress.address, this.zone.host || delivery.domain, delivery.mxPort].join(':');
                                                                            ^

TypeError: Cannot read properties of undefined (reading 'address')
    at tryConnect (C:\Users\Administrator\Desktop\zone-mta\lib\sender.js:1029:77)
    at Sender.getConnection (C:\Users\Administrator\Desktop\zone-mta\lib\sender.js:1377:9)
    at C:\Users\Administrator\Desktop\zone-mta\lib\sender.js:922:22
    at C:\Users\Administrator\Desktop\zone-mta\lib\sender.js:61:45
    at Immediate.<anonymous> (C:\Users\Administrator\Desktop\zone-mta\services\sender.js:101:32)
    at process.processImmediate (node:internal/timers:478:21)

Node.js v20.11.1
ERR! Child/default/18240 [3a94d2adf94cc63c9807] Sender process for default exited with 1
info Child/default/18412 [a2be5b17686a3ce321fe] Spawning sender process for default
info DNS/18412 Loaded DNS cache
info Sender/default/18412 [a2be5b17686a3ce321fe] Starting sending for default
info ConnPool/18412 Connection pool is ready to take connections
info Redis/18412 Redis ready to take connections
info Plugins/sender/18412 Initialized Default headers from <plugins\core\default-headers> [load time 9ms]

**Comment by louis-lau** [comment]
What does your pool and zone config look like?

**Comment by avensonk** [comment]
Hi @louis-lau , I just solved it. Thank you for response 👍
