### ISSUE TITLE
"Loop Breaker" for "sender:fetch" failed with: Error: Detected routing loop for root@example.com

### ISSUE THREAD

**Issue by ravivgolov** [zone-eu/zone-mta#386]
Any idea why I have a JS error instead of skipBounce?

```
ERR! Plugins "Loop Breaker" for "sender:fetch" failed with: Error: Detected routing loop for root@example.com
ERR! Plugins     at Object.action (/opt/zone-mta-template/node_modules/zonemta-loop-breaker/index.js:29:27)
ERR! Plugins     at /opt/zone-mta-template/node_modules/zone-mta/lib/plugin-handler.js:460:30
ERR! Plugins     at new Promise (<anonymous>)
ERR! Plugins     at PluginHandler.runHooksAsync (/opt/zone-mta-template/node_modules/zone-mta/lib/plugin-handler.js:459:21)
ERR! Plugins     at PluginHandler.runHooks (/opt/zone-mta-template/node_modules/zone-mta/lib/plugin-handler.js:498:14)
ERR! Plugins     at /opt/zone-mta-template/node_modules/zone-mta/lib/sender.js:228:29
ERR! Plugins     at /opt/zone-mta-template/node_modules/zone-mta/lib/sender.js:60:45
ERR! Plugins     at Immediate.<anonymous> (/opt/zone-mta-template/node_modules/zone-mta/services/sender.js:101:32)
ERR! Plugins     at process.processImmediate (node:internal/timers:478:21)
```

**Comment by ravivgolov** [comment]
Forgot to add the MD5 hash.

**Comment by ravivgolov** [comment]
Forgot to add the MD5 hash.
